apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-tririga-bot
  labels:
    app: my-tririga-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-tririga-bot
  template:
    metadata:
      labels:
        app: my-tririga-bot
    spec:
      containers:
      - name: my-tririga-bot
        image: <REGISTRY>/tririga-bot/my-tririga-bot:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: "Always"
        env:
        - name: PORT
          value: "8080"
        - name: API_KEY
          value: some-value
        - name: LOGGING_LEVEL
          value: WARN
        - name: BOT_NAME
          value: my-tririga-bot
        - name: SLACK_WEBHOOK_SECRET
          value: replace_with_webhook_secret
        - name: SLACK_BOT_USER_TOKEN
          value: replace_with_oauth_token
        - name: TA_INTEGRATION_ID
          value: replace_with_integration_ID
